---
collections:
  - name: community.general
    version: 3.1.0

  - name: devsec.hardening
    version: 7.6.0

roles:
  - name: dev-sec.os-hardening
    version: 6.2.0
  - name: dev-sec.ssh-hardening
    version: 9.7.0
