---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Remove packages with known issues
  apt:
    name: '{{ item }}'
    state: absent
  with_items:
    - '{{ os_security_packages_list }}'
  when: 'os_security_packages_clean'
