---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Remove packages with known issues
  apt:
    name: '{{ os_security_packages_list }}'
    state: absent
  when: 'os_security_packages_clean'
