---
- import_tasks: apt.yml
  when: ansible_distribution == 'Ubuntu'
  tags: apt

- import_tasks: sshd_config.yml
  when: ansible_distribution == 'Ubuntu'
  tags: sshd_config

- name: Deactivate Diffie-Hellman moduli less than 3072-bit long
  shell: awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.tmp && mv /etc/ssh/moduli.tmp /etc/ssh/moduli
  notify: Restart sshd

- import_tasks: create_user.yml
  when: ansible_distribution == 'Ubuntu'
  tags: create_user
