---
- import_tasks: apt.yml
  when: ansible_distribution == 'Ubuntu'
  tags: apt

- import_tasks: sshd_config.yml
  when: ansible_distribution == 'Ubuntu'
  tags: sshd_config

- import_tasks: create_user.yml
  when: ansible_distribution == 'Ubuntu'
  tags: create_user
