- name: Copy over modified sshd_config and set permissions to root/600
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: '0600'
    owner: root
    group: root
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart sshd
