---
- name: Copy over modified sshd_config and set permissions to root/600
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: '0600'
    owner: root
    group: root
    validate: '/usr/sbin/sshd -t -f %s'

- name: Deactivate Diffie-Hellman moduli less than 3072-bit long
  shell: awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.tmp && mv /etc/ssh/moduli.tmp /etc/ssh/moduli
  notify: Restart sshd
